name: Update DB
on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

jobs:
  update_db:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update db
        run: |
          python3 main.py en --mongodb_password ${{ secrets.MONGODB_PASSWORD }} --mongodb_username ${{ secrets.MONGODB_USERNAME }}
